name: AUTO DEPLOY CONTAINER

env:
   DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
   USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
   REPOSITORY_NAME: actions-example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        run: docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
      - name: Build Image
        run: docker build -t $USERNAME/$REPOSITORY_NAME:$IMAGE_TAG .
      - name: Push Image
        run: docker push $USERNAME/$REPOSITORY_NAME:$IMAGE_TAG
